### ISSUE TITLE
python3 error

### ISSUE THREAD

**Issue by guyanf** [mapnik/OGCServer#40]
ubuntu20.04
python3.8

There are some errors when I run ogcserver...

Traceback (most recent call last):
  File "/usr/local/bin/ogcserver", line 4, in <module>
    __import__('pkg_resources').run_script('ogcserver==0.1.1', 'ogcserver')
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 1469, in run_script
    script_code = compile(script_text, script_filename, 'exec')
  File "/usr/local/lib/python3.8/dist-packages/ogcserver-0.1.1-py3.8.egg/EGG-INFO/scripts/ogcserver", line 48
    print "Listening at %s:%s...." % (host,port)
          ^
SyntaxError: invalid syntax

**Comment by guyanf** [comment]
It looks like the print function's error.
